# Generated by Django 4.1.7 on 2023-03-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kebapbuilder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='additional',
            name='additional_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='maintype',
            name='main_type_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='type',
            name='type_price',
            field=models.FloatField(default=0),
        ),
    ]
